### ISSUE TITLE
current player quits on second go after first card skip first player

### ISSUE THREAD

**Issue by butlerx** [creadak/creabot#134]

**Comment by butlerx** [comment]
havent been able to replicate

**Comment by butlerx** [comment]
/storage/home/committe/butlerx/creabot/plugin_code/uno/app/models/game.js:132
    var seconds = Math.max(60, (60 * self.config.gameOptions.turnMinutes) -
                                                ^

TypeError: Cannot read property 'gameOptions' of undefined
    at self.turnTimer [as _repeat] (/storage/home/committe/butlerx/creabot/plugin_code/uno/app/models/game.js:132:49)
    at wrapper [as _onTimeout] (timers.js:276:11)
    at Timer.listOnTimeout (timers.js:93:15)

**Comment by butlerx** [comment]
happens when current player quits

**Comment by butlerx** [comment]
Appears to happen if no cards have been played

**Comment by butlerx** [comment]
heppens only if first player is skipped
